### ISSUE TITLE
Stepped slider

### ISSUE THREAD

**Issue by T8RIN** [galaxygoldfish/waveslider#1]
Is it possible to add steps like this?

![ResizedImage_Screenshot_20230531-160806_Image Resizer_2023-05-31_16-08-29_3289.png](https://github.com/galaxygoldfish/waveslider/assets/52178347/b4ce33d6-cd1b-4de2-ab70-41cacdd90838)

Maybe only when the slider is flattened, or make them invisible, while animation is running

**Comment by galaxygoldfish** [comment]
🎉🎉


![Screenshot 2023-05-31 212709](https://github.com/galaxygoldfish/waveslider/assets/77251765/93ca42a1-9021-4f52-835c-fcafca32790c)
![Screenshot 2023-05-31 212638](https://github.com/galaxygoldfish/waveslider/assets/77251765/70e6f71b-62a9-467c-9898-521c3c7d9e4f)

**Comment by T8RIN** [comment]
That's great! Thanks ❤️

**Comment by T8RIN** [comment]
That's great! Thanks ❤️
